server:
  port : 8121
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

app:
    source: C:/Trainings/input?fileName=Test_Demo.txt
    destination: C:/Trainings/output/